version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: BookCollabSaaS.Presentation/Dockerfile
  #   ports:
  #     - "8090:8090"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__Redis=redis:6379,abortConnect=false
  #   depends_on:
  #     - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
